Created footer and burger_menu without adaptive
fe-jan23-cyber-sapiens/products_catalog pull request #5
Opened 2023-05-09 19:37 UTC by Yevhenii0536

2023-05-09 20:48 UTC, KuharchukDmytro requested changes

2023-05-09 20:48 UTC, KuharchukDmytro commented on src/BurgerMenu/BurgerMenu.tsx
> +            </a>
use link from react-router

2023-05-09 20:48 UTC, KuharchukDmytro commented on src/Footer/Footer.scss
> +    box-sizing: border-box;
this property in normalize file, u can delete it

2023-05-09 20:48 UTC, KuharchukDmytro commented on src/Footer/Footer.scss
> +    height: 96px;
height duplicating, and for such global properties better to use variables

2023-05-09 20:48 UTC, KuharchukDmytro commented on src/Footer/Footer.tsx
> +          <a className="footer-nav_link" href="/">
wrong bem usage
```suggestion
          <a className="footer-nav__link" href="/">
```

2023-05-10 13:29 UTC, lilia-obushenko approved these changes

2023-05-10 14:16 UTC, KuharchukDmytro approved these changes

2023-05-10 15:13 UTC, KuharchukDmytro approved these changes

2023-05-10 15:20 UTC, merged