Grid done
fe-jan23-cyber-sapiens/products_catalog pull request #9
Opened 2023-05-10 14:10 UTC by DenysDubas

2023-05-11 10:17 UTC, KuharchukDmytro requested changes

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/componentsOfCartExample/productsCart/productsCart.tsx
> +    setQuantity(count + 1);
```suggestion
    setCount(prev => prev + 1);
    setQuantity(prev => prev + 1);
```

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/componentsOfCartExample/productsCart/productsCart.tsx
> +import { Delete } from '@material-ui/icons';
add package,json

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/componentsOfCartExample/cartsCheckout/checkout.scss
> +}
remove

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/componentsOfCartExample/cartsCard/card.tsx
> +// import '../../App.scss';
remove

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/App.tsx
> +// App.tsx
remove

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/container/container.scss
> +}
remove

2023-05-11 10:17 UTC, KuharchukDmytro commented on src/container/container.scss
> +@media only screen and (min-width: 768px) and (max-width: 1198px) {
use mixins

2023-05-12 05:02 UTC, lilia-obushenko approved these changes

2023-05-12 17:21 UTC, KuharchukDmytro approved these changes

2023-05-12 17:22 UTC, merged